### ISSUE TITLE
Running mix deps.get won't add the command lingex.build, lingex.build_image or lingex.image

### ISSUE THREAD

**Issue by sashaafm** [maximk/lingex#4]
I'm trying to run my app on Xen, and I'm following the Elixir on Xen guide, but when I run the dependencies and check mix help, the commands for lingex are not there. When I run mix lingex.build_image also says it doesn't have that command.

Any help?

**Comment by maximk** [comment]
We stopped using the build service (a couple of years ago). It will take considerable effort to restore Elixir support and it is not in the plans. I am afraid you are on your own.

**Comment by sashaafm** [comment]
Then I guess there's now way to use Elixir on Xen? Thanks anyway

**Comment by maximk** [comment]
No, unless you are willing to restore the support yourself :-)

**Comment by sashaafm** [comment]
I see :( I really wanted to use it for my project. I'll see if I have the time and knowledge to invest into supporting it, but I doubt it. Thanks for your time maxim.
